### ISSUE TITLE
I'm not finding the function IMPINJ_ENABLE_EXTENSIONS_Message

### ISSUE THREAD

**Issue by pietrothebest** [esitarski/pyllrp#6]
I'm using the example TinyExample.py
I'm not finding the function IMPINJ_ENABLE_EXTENSIONS_Message:

```
Traceback (most recent call last):
  File ".\TesteImpinj\main.py", line 113, in <module>
    CustomExtensionTest( reader )
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File ".\TesteImpinj\main.py", line 25, in CustomExtensionTest
    message = IMPINJ_ENABLE_EXTENSIONS_Message( MessageID = 0xeded )
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'IMPINJ_ENABLE_EXTENSIONS_Message' is not defined
```

Outras funções também não estão sendo encontradas:
- GET_READER_CONFIG_Message
- GetReaderConfigRequestedData
- ImpinjReaderTemperature_Parameter

**Comment by esitarski** [comment]
You didn't attach your source code, but my guess is that you are missing the following line:

`from pyllrp import *`

Alternatively, you could do:

```
import pyllrp
...
message = pyllrp.IMPINJ_ENABLE_EXTENSIONS_Message( MessageID = 0xeded )
...
```
If it was important to stay within the pyllrp namespace.

**Comment by LeoDJ** [comment]
Same problem for me.
I just tried to run the TinyExample.py from this repository and it can't find a bunch of methods / variables.

Is the example out of date?
